spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kurzelakamil/config-files
encrypt:
  key: ${ENCRYPT_KEY}

server:
  port: ${PORT}

---
spring:
  profiles: local

server:
  port: 8888
