spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kurzelakamil/config-files
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}

encrypt:
  key: ${ENCRYPT_KEY}

server:
  port: ${CONFIG_SERVER_PORT}
